# Матрицы и матричные операции.

In [42]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   

In [43]:
A = np.array([[1, 7], [4, -3],[2, 8], [1, 7]])
B = np.array([[0, 3], [1, 6], [1 ,-2], [-5, -4]])

In [44]:
print(f'AB\n{np.dot(A, B)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [45]:
print(f'AB\n{np.dot(B, A)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

  б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - неопределена; $BA$ - $2\times 3$


In [46]:
A = np.array([[2, 3, 1, 5, 5], [2, 3, 2, 1, 2]])
B = np.array([[2, 3, 1], [1, 0, 0],  [3, 1, 2], [1, 1, 4], [3, 5, 20]])

In [47]:
print(f'AB\n{np.dot(A, B)}')

AB
[[ 30  37 124]
 [ 20  19  50]]


In [48]:
print(f'BA\n{np.dot(B, A)}')

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$

In [49]:
A = np.array([[1, 2, 4], [5, 6, 1], [2 ,0, -1], [3, 4, 1], [4 ,-1, 5], [2 ,-1, 0], [2 ,8, 1], [8 ,-2, 1]])
B = np.array([[1, 7, 5, 4, 5, 5, 5, 2], [3, -1, 4, -3, 2, -3, 4, -11], [3, -6, 1, 7, 3, -4, 4, 11]])

In [50]:
print(f'AB\n{np.dot(A, B)}')

AB
[[ 19 -19  17  26  21 -17  29  24]
 [ 26  23  50   9  40   3  53 -45]
 [ -1  20   9   1   7  14   6  -7]
 [ 18  11  32   7  26  -1  35 -27]
 [ 16  -1  21  54  33   3  36  74]
 [ -1  15   6  11   8  13   6  15]
 [ 29   0  43  -9  29 -18  46 -73]
 [  5  52  33  45  39  42  36  49]]


In [51]:
print(f'AB\n{np.dot(B, A)}')

AB
[[114  86  42]
 [-81  43   7]
 [ 96   9  42]]


г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

In [52]:
A = np.array([[1, 2, 3, 1], [2, 3, 3, 3], [2, -2, 0, 1], [7, 7, 5, 1]])
B = np.array([[1, 3, 5, 7], [8, 8, 9, 2], [2, -4, 4, 3], [0, -4, 3, -9]])

In [53]:
print(f'AB\n{np.dot(A, B)}')

AB
[[ 23   3  38  11]
 [ 32   6  58   2]
 [-14 -14  -5   1]
 [ 73  53 121  69]]


In [54]:
print(f'AB\n{np.dot(B, A)}')

AB
[[ 66  50  47  22]
 [ 56  36  58  43]
 [ 23   5   9  -3]
 [-65 -81 -57 -18]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

In [55]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [56]:
#сумма
print(A + B)

[[ 5 -3]
 [ 3  5]]


In [57]:
#произведение
print(np.dot(A, B))

[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [62]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

print(f"3𝐴 − 2𝐵 + 4𝐶 = \n{A*3+(-2)*B+4*C}")

3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [59]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
print(np.dot(A, At))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [32]:
print(np.dot(At, A))

[[45  0]
 [ 0 14]]



__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [27]:
a = np.array([[np.sin(1), -(np.cos(1))], [np.cos(1), np.sin(1)]])
print(np.linalg.det(a))

1.0


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [28]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(np.linalg.det(a))

180.0


__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [26]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(np.linalg.det(a))

0.0


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [25]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

print(np.linalg.matrix_rank(a))

2
